"""Añadida clave foranea

Revision ID: 8eea4669af17
Revises: d09b3a4480ca
Create Date: 2025-05-16 11:24:29.244987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8eea4669af17'
down_revision: Union[str, None] = 'd09b3a4480ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.Column('apellido', sa.String(length=60), nullable=True),
    sa.Column('Tipo_de_documento', sa.String(length=60), nullable=True),
    sa.Column('numero_de_documento', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.Column('apellido', sa.String(length=60), nullable=True),
    sa.Column('especialidad', sa.String(length=60), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['Pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('paciente')
    op.drop_table('medico')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medico',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('apellido', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('especialidad', mysql.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='armscii8_bin',
    mysql_default_charset='armscii8',
    mysql_engine='InnoDB'
    )
    op.create_table('paciente',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('apellido', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('Tipo_de_documento', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('numero_de_documento', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('telefono', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='armscii8_bin',
    mysql_default_charset='armscii8',
    mysql_engine='InnoDB'
    )
    op.drop_table('Medicos')
    op.drop_table('Pacientes')
    # ### end Alembic commands ###
